FROM python:3.11.3 as python

COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip && pip install -r ./requirements.txt

WORKDIR /app
COPY . /app

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]
